---
- name: debug the docker package
  debug:
    var:  docker_package["Debian"]
  tags:
    - docker
    - debug

- name: Remove existing docker-lxc if present
  apt:
    name: lxc-docker
    purge: yes
    state: absent
  tags:
    - docker

- name: Set correct policy for Docker
  shell: apt-cache policy docker-engine

- name: Ensure that Docker Engine is on the host
  apt:
    name: "{{ docker_package[ansible_os_family] }}"
    state: present
    update_cache: yes
  tags:
    - docker

# See https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin
- name: Configure Docker Opts for Jenkins
  lineinfile:
    dest: /etc/init/docker.conf
    regexp: 'DOCKER_OPTS=.*'
    line: 'DOCKER_OPTS="-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"'
    backrefs: yes
  #  validate: 'source %s'
  tags:
    - docker

# see http://docs.ansible.com/ansible/docker_image_module.html and http://docs.ansible.com/ansible/docker_module.html
- name: Preqrequisites for Ansible Docker
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - requests
    - docker-py
  tags:
    - docker

- name: ensure docker is running
  service:
    name: docker
    state: started
  tags:
    - docker

# This is the preconfigured jenkins build slave. It has a jenkins user and an ssh server
- name: pull a build slave
  docker:
    docker_url: unix://var/run/docker.sock
    name: docker-buildslave
    image: evarga/jenkins-slave
    state: reloaded
    pull: always
    insecure_registry: true
    docker_api_version: 1.22
  tags:
    - docker

# See http://bsaunder.github.io/2014/12/21/running-docker-without-sudo/
- name: Give Docker to Jenkins
  user:
    name: jenkins
    groups: jenkins,sudo,docker
    append: yes
