---
# Jenkins jobs

- name: Get the list of jenkins jobs
  command: >
     java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/ list-jobs
  register: jobs
  tags:
    - jenkinsJobs

- name: what jobs are there ?
  debug:
    var: jobs.stdout_lines
  changed_when: false
  tags:
    - jenkinsJobs


- name: delete existing hello-world
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/ delete-job hello-world
  when: "{{ 'hello-world' in jobs.stdout_lines }}"
  tags:
    - jenkinsJobs

- name: push the hello world job template
  copy:
    src: helloworld-container.xml
    dest: /tmp/config.xml
  tags:
    - jenkinsJobs

- name: Create basic hello-world job
  shell: >
      java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/ create-job < /tmp/config.xml
  args:
    creates: /var/lib/jenkins/jobs/hello-world/config.xml
  tags:
    - jenkinsJobs
