---
# prerequistes for the jenkins server on Debian
- name: Ensure prerequiste packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{  prerequisites }}"

# We will add these to a var later

- name: Ensure the correct ports are open (8080)
  ufw:
    direction: in
    #name: jenkins
    proto: tcp
    rule: allow
    from_port: 8080


- name: Ensure Jenkins is present
  package:
    name: "jenkins"
    state: latest
